# Generated by Django 5.0.2 on 2024-02-26 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysuserprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^\\d{10}$')]),
        ),
    ]
