# Generated by Django 5.0.2 on 2024-04-01 16:09

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('sysuserprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_number', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Error ID/RUC/Pasaporte no válido!', regex='(^\\d{10}|^[a-zA-Z0-9]*)$')])),
                ('id_type', models.CharField(choices=[('CI', 'CI'), ('RUC', 'RUC'), ('PP', 'Pasaporte')], default='None', max_length=3, null=True)),
                ('client_type', models.CharField(choices=[('P', 'prospecto'), ('C', 'cliente')], default='P', max_length=2)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('sur_name', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, height_field=300, null=True, upload_to='media/clients/', width_field=300)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default=None, max_length=2, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('s', 'Soltero(a)'), ('c', 'Casado(a)'), ('d', 'Divorciado(a)'), ('v', 'Viudo(a)')], default=None, max_length=2, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(blank=True, default=None, max_length=100, null=True)),
                ('person_type', models.CharField(blank=True, choices=[('N', 'Natural'), ('J', 'Jurídica')], default=None, max_length=4, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('budget_capacity', models.CharField(blank=True, choices=[('l', 'Bajo'), ('ml', 'Medio-bajo'), ('m', 'Medio'), ('mh', 'Medio-alto'), ('h', 'Alto')], default=None, max_length=2, null=True)),
                ('academic_level', models.CharField(blank=True, choices=[('PR', 'Primaria'), ('HS', 'Secundaria'), ('UN', 'Universitaria'), ('BA', 'Licenciatura'), ('MA', 'Maestría'), ('PH', 'Doctorado')], default=None, max_length=2, null=True)),
                ('work_type', models.CharField(blank=True, choices=[('I', 'Independiente'), ('D', 'Dependiente')], default=None, max_length=2, null=True)),
                ('work_industry', models.CharField(blank=True, choices=[('AGRI', 'Agricultura'), ('ARTS', 'Arte'), ('BSNS', 'Negocios'), ('COMM', 'Comunicación'), ('TECH', 'Ciencias computacionales / Tecnología'), ('HLTH', 'Salud / Medicina'), ('EDUC', 'Educación'), ('FOOD', 'Alimentos / Servicios culinarios'), ('ENGR', 'Ingeniería'), ('GOVT', 'Gobierno'), ('HMKR', 'Amo(a) de casa'), ('LEGL', 'Servicios legales'), ('MLTY', 'Servicios militares'), ('SCNC', 'Ciencias naturales'), ('UNPY', 'Sin empleo'), ('PYSI', 'Deportes / Actividad física'), ('RLGN', 'Servicios religiosos'), ('RSCH', 'Investigación'), ('RTRD', 'Jubilado(a)'), ('STDN', 'Estudiante'), ('OTHR', 'Otro(s)')], default=None, max_length=5, null=True)),
                ('work_position', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, default=None, max_length=100, null=True)),
                ('res_city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('salesman_refer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sysuserprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('passport_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passport_type', models.CharField(choices=[('TRS', 'Visa de turista ()'), ('STU', 'Visa de estudiante ()'), ('WRK', 'Visa de trabajo ()'), ('BSN', 'Visa de negocios ()'), ('FAM', 'Visa familiar ()'), ('TRA', 'Visa de tránsito ()'), ('DIP', 'Visa diplomática ()'), ('OFF', 'Visa oficial ()'), ('REL', 'Visa religiosa ()'), ('MED', 'Visa médica ()'), ('REF', 'Visa de refugiado ()'), ('IMM', 'Visa de inmigrante ()')], max_length=3)),
                ('passport_issue_date', models.DateField()),
                ('passport_expire_date', models.DateField()),
                ('passport_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('passport_issue_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.country')),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('visa_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('visa_type', models.CharField(choices=[('TRS', 'Visa de turista ()'), ('STU', 'Visa de estudiante ()'), ('WRK', 'Visa de trabajo ()'), ('BSN', 'Visa de negocios ()'), ('FAM', 'Visa familiar ()'), ('TRA', 'Visa de tránsito ()'), ('DIP', 'Visa diplomática ()'), ('OFF', 'Visa oficial ()'), ('REL', 'Visa religiosa ()'), ('MED', 'Visa médica ()'), ('REF', 'Visa de refugiado ()'), ('IMM', 'Visa de inmigrante ()')], default='T', max_length=3)),
                ('visa_issue_date', models.DateField()),
                ('visa_expire_date', models.DateField()),
                ('visa_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('visa_to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.country')),
            ],
        ),
    ]
