# Generated by Django 5.0.2 on 2024-04-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_res_country_client_res_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('PR', 'Primaria'), ('HS', 'Secundaria'), ('SU', 'Superior'), ('PG', 'Posgrado')], default=None, max_length=2, null=True),
        ),
    ]
