# Generated by Django 5.0.2 on 2024-03-04 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_city_alter_client_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('s', 'Soltero(a)'), ('c', 'Casado(a)'), ('d', 'Divorciado(a)'), ('v', 'Viudo(a)')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='La longitud debe ser de 10!', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_type',
            field=models.CharField(choices=[('CI', 'CI'), ('RUC', 'RUC')], default='CI', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Number must has the 09XXXXXXXX structure', regex='^09\\d{8}$')]),
        ),
    ]
