# Generated by Django 5.0.2 on 2024-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_academic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(height_field=300, null=True, upload_to='clientes', width_field=300),
        ),
    ]
