# Generated by Django 5.0.2 on 2024-03-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_civil_status_alter_client_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_type',
            field=models.CharField(choices=[('CI', 'CI'), ('RUC', 'RUC'), ('PP', 'Pasaporte')], default='CI', max_length=3, null=True),
        ),
    ]
