# Generated by Django 5.0.2 on 2024-04-06 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('clients', '0004_alter_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(null=True, upload_to='clients_photos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='res_city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='client',
            name='res_country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='res_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='cities_light.region'),
        ),
    ]
