# Generated by Django 5.0.2 on 2024-03-07 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Error ID/RUC/Pasaporte no válido!', regex='(^\\d{10}|^\\d{13}|^w*)$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_type',
            field=models.CharField(choices=[('CI', 'CI'), ('RUC', 'RUC'), ('PP', 'Pasaporte')], default=None, max_length=3, null=True),
        ),
    ]
