# Generated by Django 5.0.2 on 2024-03-08 16:48

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_id_number_alter_client_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='media/clients/', width_field=300),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Error ID/RUC/Pasaporte no válido!', regex='(^\\d{10}||^w*)$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
