# Generated by Django 5.0.2 on 2024-03-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('clients', '0008_alter_client_id_number_alter_client_id_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='client',
            name='province',
        ),
        migrations.AddField(
            model_name='client',
            name='res_city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='client',
            name='res_coutry',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='res_province',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
