# Generated by Django 5.0.2 on 2024-03-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_client_res_coutry_alter_client_res_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='res_coutry',
        ),
        migrations.RemoveField(
            model_name='client',
            name='res_province',
        ),
    ]
