# Generated by Django 5.0.2 on 2024-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_remove_client_res_coutry_remove_client_res_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='work_type',
            field=models.CharField(blank=True, choices=[('I', 'Independiente'), ('D', 'Dependiente')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_industry',
            field=models.CharField(blank=True, choices=[('TECH', 'Tecnología de la Información (IT)'), ('HLTH', 'Salud'), ('EDUC', 'Educación'), ('ACCT', 'Contabilidad'), ('PHRM', 'Farmacéutica'), ('FINC', 'Finanzas'), ('ENGR', 'Ingeniería'), ('RALT', 'Bienes Raíces'), ('HEDU', 'Educación Superior'), ('SLES', 'Ventas'), ('GOVT', 'Gobierno'), ('NRGY', 'Energía'), ('RETL', 'Venta al por Menor'), ('MFGT', 'Manufactura'), ('ARCH', 'Arquitectura'), ('HURE', 'Recursos Humanos'), ('NPRF', 'Sin Fines de Lucro'), ('TRSP', 'Transporte'), ('HOSP', 'Hospitalidad')], default=None, max_length=5, null=True),
        ),
    ]
