# Generated by Django 5.0.2 on 2024-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_work_type_alter_client_work_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('PR', 'Primaria'), ('HS', 'Secundaria'), ('UN', 'Universitaria'), ('BA', 'Licenciatura'), ('MA', 'Maestría'), ('PH', 'Doctorado')], default=None, max_length=2, null=True),
        ),
    ]
