# Generated by Django 5.0.2 on 2024-03-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_academic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, default='media/clients/default.jpg', height_field=300, null=True, upload_to='media/clients/', width_field=300),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_industry',
            field=models.CharField(blank=True, choices=[('AGRI', 'Agricultura'), ('ARTS', 'Arte'), ('BSNS', 'Negocios'), ('COMM', 'Comunicación'), ('TECH', 'Ciencias computacionales / Tecnología'), ('HLTH', 'Salud / Medicina'), ('EDUC', 'Educación'), ('FOOD', 'Alimentos / Servicios culinarios'), ('ENGR', 'Ingeniería'), ('GOVT', 'Gobierno'), ('HMKR', 'Amo(a) de casa'), ('LEGL', 'Servicios legales'), ('MLTY', 'Servicios militares'), ('SCNC', 'Ciencias naturales'), ('UNPY', 'Sin empleo'), ('PYSI', 'Deportes / Actividad física'), ('RLGN', 'Servicios religiosos'), ('RSCH', 'Investigación'), ('RTRD', 'Jubilado(a)'), ('STDN', 'Estudiante'), ('OTHR', 'Otro(s)')], default=None, max_length=5, null=True),
        ),
    ]
