# Generated by Django 4.2.5 on 2024-03-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_client_image_alter_client_work_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='media/clients/', width_field=300),
        ),
    ]
