# Generated by Django 5.0.2 on 2024-03-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_alter_client_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='academic_level',
        ),
        migrations.RemoveField(
            model_name='client',
            name='work_type',
        ),
        migrations.AlterField(
            model_name='client',
            name='work_industry',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
