# Generated by Django 5.0.2 on 2024-03-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_remove_client_academic_level_remove_client_work_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('PR', 'Primaria'), ('HS', 'Secundaria'), ('UN', 'Universitaria'), ('BA', 'Licenciatura'), ('MA', 'Maestría'), ('PH', 'Doctorado')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='work_type',
            field=models.CharField(blank=True, choices=[('I', 'Independiente'), ('D', 'Dependiente')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_industry',
            field=models.CharField(blank=True, choices=[('AGRI', 'Agricultura'), ('ARTS', 'Arte'), ('BSNS', 'Negocios'), ('COMM', 'Comunicación'), ('TECH', 'Ciencias computacionales / Tecnología'), ('HLTH', 'Salud / Medicina'), ('EDUC', 'Educación'), ('FOOD', 'Alimentos / Servicios culinarios'), ('ENGR', 'Ingeniería'), ('GOVT', 'Gobierno'), ('HMKR', 'Amo(a) de casa'), ('LEGL', 'Servicios legales'), ('MLTY', 'Servicios militares'), ('SCNC', 'Ciencias naturales'), ('UNPY', 'Sin empleo'), ('PYSI', 'Deportes / Actividad física'), ('RLGN', 'Servicios religiosos'), ('RSCH', 'Investigación'), ('RTRD', 'Jubilado(a)'), ('STDN', 'Estudiante'), ('OTHR', 'Otro(s)')], default=None, max_length=5, null=True),
        ),
    ]
